### ISSUE TITLE
Time-out a spammy user

### ISSUE THREAD

**Issue by nxusr** [ejamesc/jarvisbot#8]
Either of the following would be nice:
- Rate limit each command from a user
- /timeout @username [duration-with-a-cap?]

**Comment by ejamesc** [comment]
Is this still necessary? I think the challenge is to implement this fairly, but I don't think this is a big deal yet. (Maybe for Channels, if I ever enable Jarvis for Channels).

I'm going to close and mark as 'will not fix', but let's KIV for the future.
